// Auto-generated by scripts/compute-static-data.ts — do not edit manually

export const STATIC_GAME_STATS = {
  "totalGames": 4271,
  "controlRounds": 1308,
  "hiddenAgendaRounds": 2963
} as const

export const STATIC_RANKINGS = [
  {
    "modelId": "xai/grok-4.1-fast-reasoning",
    "displayName": "Grok 4.1 Fast Reasoning",
    "totalPoints": 23897,
    "gamesPlayed": 1197,
    "wins": 583,
    "losses": 29
  },
  {
    "modelId": "anthropic/claude-sonnet-4.5",
    "displayName": "Claude Sonnet 4.5",
    "totalPoints": 23691,
    "gamesPlayed": 1200,
    "wins": 32,
    "losses": 575
  },
  {
    "modelId": "openai/gpt-5.1-thinking",
    "displayName": "GPT-5.1 Thinking",
    "totalPoints": 21007,
    "gamesPlayed": 1118,
    "wins": 389,
    "losses": 220
  },
  {
    "modelId": "google/gemini-3-pro-preview",
    "displayName": "Gemini 3 Pro Preview",
    "totalPoints": 20304,
    "gamesPlayed": 1045,
    "wins": 495,
    "losses": 127
  },
  {
    "modelId": "anthropic/claude-opus-4.5",
    "displayName": "Claude Opus 4.5",
    "totalPoints": 18917,
    "gamesPlayed": 998,
    "wins": 33,
    "losses": 499
  },
  {
    "modelId": "perplexity/sonar-pro",
    "displayName": "Sonar Pro",
    "totalPoints": 18548,
    "gamesPlayed": 1044,
    "wins": 223,
    "losses": 325
  },
  {
    "modelId": "moonshotai/kimi-k2-thinking-turbo",
    "displayName": "Kimi K2 Thinking Turbo",
    "totalPoints": 18046,
    "gamesPlayed": 1045,
    "wins": 399,
    "losses": 264
  },
  {
    "modelId": "deepseek/deepseek-v3.2-thinking",
    "displayName": "DeepSeek V3.2 Thinking",
    "totalPoints": 11893,
    "gamesPlayed": 837,
    "wins": 185,
    "losses": 300
  }
] as const

export const STATIC_STRATEGY_STATS = {
  "forgiving": 1849,
  "forgivingTotal": 40242,
  "retaliating": 37006,
  "retaliatingTotal": 40242,
  "nice": 5815,
  "niceTotal": 8746,
  "nonEnvious": 6431,
  "nonEnviousTotal": 8746
} as const

export const STATIC_SCENARIO_STATS = {
  "overt": {
    "cooperate": 25352,
    "defect": 321,
    "total": 26372
  },
  "sales": {
    "cooperate": 4361,
    "defect": 17346,
    "total": 22724
  },
  "research": {
    "cooperate": 3457,
    "defect": 16356,
    "total": 20318
  },
  "creator": {
    "cooperate": 5707,
    "defect": 11245,
    "total": 17474
  }
} as const

export interface StaticModelDetailedStats {
  modelId: string
  displayName: string
  totalGames: number
  totalPoints: number
  totalErrors: number
  wins: number
  losses: number
  ties: number
  behavior: {
    forgiving: number
    forgivingTotal: number
    retaliating: number
    retaliatingTotal: number
    nice: number
    niceTotal: number
    nonEnvious: number
    nonEnviousTotal: number
  }
}

export const STATIC_MODEL_DETAILS: Record<string, StaticModelDetailedStats> = {
  "deepseek/deepseek-v3.2-thinking": {
    "modelId": "deepseek/deepseek-v3.2-thinking",
    "displayName": "DeepSeek V3.2 Thinking",
    "totalGames": 837,
    "totalPoints": 11893,
    "totalErrors": 1969,
    "wins": 185,
    "losses": 300,
    "ties": 352,
    "behavior": {
      "forgiving": 35,
      "forgivingTotal": 4383,
      "retaliating": 3200,
      "retaliatingTotal": 4383,
      "nice": 496,
      "niceTotal": 931,
      "nonEnvious": 805,
      "nonEnviousTotal": 931
    }
  },
  "moonshotai/kimi-k2-thinking-turbo": {
    "modelId": "moonshotai/kimi-k2-thinking-turbo",
    "displayName": "Kimi K2 Thinking Turbo",
    "totalGames": 1045,
    "totalPoints": 18046,
    "totalErrors": 166,
    "wins": 399,
    "losses": 264,
    "ties": 382,
    "behavior": {
      "forgiving": 376,
      "forgivingTotal": 5704,
      "retaliating": 5279,
      "retaliatingTotal": 5704,
      "nice": 474,
      "niceTotal": 1067,
      "nonEnvious": 661,
      "nonEnviousTotal": 1067
    }
  },
  "perplexity/sonar-pro": {
    "modelId": "perplexity/sonar-pro",
    "displayName": "Sonar Pro",
    "totalGames": 1044,
    "totalPoints": 18548,
    "totalErrors": 300,
    "wins": 223,
    "losses": 325,
    "ties": 496,
    "behavior": {
      "forgiving": 255,
      "forgivingTotal": 5191,
      "retaliating": 4770,
      "retaliatingTotal": 5191,
      "nice": 664,
      "niceTotal": 1055,
      "nonEnvious": 825,
      "nonEnviousTotal": 1055
    }
  },
  "google/gemini-3-pro-preview": {
    "modelId": "google/gemini-3-pro-preview",
    "displayName": "Gemini 3 Pro Preview",
    "totalGames": 1045,
    "totalPoints": 20304,
    "totalErrors": 75,
    "wins": 495,
    "losses": 127,
    "ties": 423,
    "behavior": {
      "forgiving": 16,
      "forgivingTotal": 5179,
      "retaliating": 5155,
      "retaliatingTotal": 5179,
      "nice": 564,
      "niceTotal": 1061,
      "nonEnvious": 546,
      "nonEnviousTotal": 1061
    }
  },
  "xai/grok-4.1-fast-reasoning": {
    "modelId": "xai/grok-4.1-fast-reasoning",
    "displayName": "Grok 4.1 Fast Reasoning",
    "totalGames": 1197,
    "totalPoints": 23897,
    "totalErrors": 50,
    "wins": 583,
    "losses": 29,
    "ties": 585,
    "behavior": {
      "forgiving": 5,
      "forgivingTotal": 5786,
      "retaliating": 5776,
      "retaliatingTotal": 5786,
      "nice": 545,
      "niceTotal": 1210,
      "nonEnvious": 617,
      "nonEnviousTotal": 1210
    }
  },
  "anthropic/claude-sonnet-4.5": {
    "modelId": "anthropic/claude-sonnet-4.5",
    "displayName": "Claude Sonnet 4.5",
    "totalGames": 1200,
    "totalPoints": 23691,
    "totalErrors": 58,
    "wins": 32,
    "losses": 575,
    "ties": 593,
    "behavior": {
      "forgiving": 279,
      "forgivingTotal": 4636,
      "retaliating": 4356,
      "retaliatingTotal": 4636,
      "nice": 1211,
      "niceTotal": 1215,
      "nonEnvious": 1176,
      "nonEnviousTotal": 1215
    }
  },
  "anthropic/claude-opus-4.5": {
    "modelId": "anthropic/claude-opus-4.5",
    "displayName": "Claude Opus 4.5",
    "totalGames": 998,
    "totalPoints": 18917,
    "totalErrors": 50,
    "wins": 33,
    "losses": 499,
    "ties": 466,
    "behavior": {
      "forgiving": 866,
      "forgivingTotal": 3880,
      "retaliating": 3014,
      "retaliatingTotal": 3880,
      "nice": 1018,
      "niceTotal": 1022,
      "nonEnvious": 1003,
      "nonEnviousTotal": 1022
    }
  },
  "openai/gpt-5.1-thinking": {
    "modelId": "openai/gpt-5.1-thinking",
    "displayName": "GPT-5.1 Thinking",
    "totalGames": 1118,
    "totalPoints": 21007,
    "totalErrors": 75,
    "wins": 389,
    "losses": 220,
    "ties": 509,
    "behavior": {
      "forgiving": 17,
      "forgivingTotal": 5483,
      "retaliating": 5456,
      "retaliatingTotal": 5483,
      "nice": 785,
      "niceTotal": 1127,
      "nonEnvious": 740,
      "nonEnviousTotal": 1127
    }
  }
} as const
